name: ci

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.6
          architecture: x64
      - name: Maven package
        run: mvn -B package --file ./mvc-java-spring-boot-template-web/pom.xml
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Docker build
        run: docker buildx build --platform linux/amd64,linux/arm64 -t vartdalen/mvc-java-spring-boot-template:latest ./mvc-java-spring-boot-template-web/.
        if: ${{ !(github.event_name == 'push' && github.ref == 'refs/heads/master') }}
      - name: Docker build and push
        run: docker buildx build --platform linux/amd64,linux/arm64 -t vartdalen/mvc-java-spring-boot-template:latest ./mvc-java-spring-boot-template-web/. --push
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
